config system global
 set hostname "FGT-02"
end

config system ha
 set group-name "FGT-HA-LAB"
 set group-id 10
 set mode a-p
 set password password
 set hbdev "port4" 100 "port5" 50
 set session-pickup enable
 set override disable
 set priority 100
end
