hostname SW-EDGE
no ip domain-lookup
spanning-tree mode rapid-pvst

banner motd ^CUnauthorized access prohibited - LAB^C

vlan 100
 name WAN_TRANSIT

interface e0/1
 description TO_FGT01
 switchport mode access
 switchport access vlan 100
 spanning-tree portfast
 no shutdown

interface e0/2
 description TO_FGT02
 switchport mode access
 switchport access vlan 100
 spanning-tree portfast
 no shutdown

interface e0/0
 description TO_INTERNET
 switchport mode access
 switchport access vlan 100
 spanning-tree portfast
 no shutdown
